#language: java
#
#
#
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#
#jdk:
#  - oraclejdk8
#
#sudo: false
#
#before_install:
#- npm install gulp gulp-mocha gulp-util chai
#- sudo apt-get update
#- sudo apt-get install scala
#script: "gradle build"
#
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
#
#notifications:
#  email: false
#  slack: recolonize:wXbXAFYJpkuxt6VouW0Xt2dd
#
 language: java
 before_install:
 - npm install gulp gulp-mocha gulp-util chai
 - sudo apt-get update
 - sudo apt-get install scala
 script: "gradle build"